In [1]:
import numpy as np
import math

# Matrizes de rotação 

## Matrizes de rotação para cada eixo:
### a) Eixo X:



In [18]:
def rotX(theta):

    return np.array([[1, 0, 0],
                   [0, np.cos(theta), -np.sin(theta)],
                   [0, np.sin(theta), np.cos(theta)]])
    

### b) Eixo Y:


In [17]:
def rotY(theta):

    return np.array([  [np.cos(theta), 0, np.sin(theta)],
                                [0, 1, 0],
                                [-np.sin(theta), 0, np.cos(theta)]])

### Eixo Z: 

In [16]:
def rotZ(theta):

    return np.array([  [np.cos(theta), -np.sin(theta), 0],
                                [np.sin(theta), np.cos(theta), 0],
                                [0, 0, 1]])

## Transformações em relações as referências 
### a) Fixa (eixo inercial): Pré-multiplicação 
### b) Móvel (eixo no corpo): Pós-multiplicação 

## Input do usuário 


In [23]:
numRot_str = input("Número de rotações: ")
numRot_int = int(numRot_str)

ref = int(input("Transformação em relação a referência fixa (0) ou móvel (1): "))

eixosRot = []
angulos = []

for i in range(numRot_int):
    print("Rotação ", i)
    eixo = input("Entre com o eixo da rotação (x, y ou z): ")
    ang = np.radians(float(input("Entre com o ângulo de rotação em graus: ")))

    if ref:
        eixosRot.append(eixo)
        angulos.append(ang)
    else:
        eixosRot.insert(0, eixo)
        angulos.insert(0, ang)

    print("Tipo da rotação fixa (0) ou móvel (1): ", ref)
    print("Ângulo da rotação: ", angulos[i])
    print("Eixo da rotação: ", eixosRot[i])
    print("-------------------------")


Rotação  0
Tipo da rotação fixa (0) ou móvel (1):  0
Ângulo da rotação:  1.0471975511965976
Eixo da rotação:  y
-------------------------
Rotação  1
Tipo da rotação fixa (0) ou móvel (1):  0
Ângulo da rotação:  1.0471975511965976
Eixo da rotação:  y
-------------------------
Rotação  2
Tipo da rotação fixa (0) ou móvel (1):  0
Ângulo da rotação:  1.0471975511965976
Eixo da rotação:  y
-------------------------
Rotação  3
Tipo da rotação fixa (0) ou móvel (1):  0
Ângulo da rotação:  1.0471975511965976
Eixo da rotação:  y
-------------------------


## Cálculo da composição

In [24]:
matrizComp = []

if eixosRot[0] == 'x':
    matrizComp = rotX(angulos[0])
if eixosRot[0] == 'y':
    matrizComp = rotY(angulos[0])
if eixosRot[0] == 'z':
    matrizComp = rotZ(angulos[0])

for i in range(1, numRot_int):
    if eixosRot[i] == 'x':
        matrizComp = np.matmul(matrizComp, rotX(angulos[i]))
    if eixosRot[i] == 'y':
        matrizComp = np.matmul(matrizComp, rotY(angulos[i]))
    if eixosRot[i] == 'z':
        matrizComp = np.matmul(matrizComp, rotZ(angulos[i]))
        
print(matrizComp)

[[ 0.25538596 -0.03085512  0.96634672]
 [ 0.65580384  0.73994211 -0.14968964]
 [-0.71042194  0.67196252  0.20920573]]


## Rotação do vetor

In [26]:
x = int(input("Entre com a componte x do vetor P: "))
y = int(input("Entre com a componte y do vetor P: "))
z = int(input("Entre com a componte z do vetor P: "))

p = np.array([x, y, z])

print("Vetor não rotacionado: ", p)

p_rot = np.round(np.matmul(matrizComp, p), 3)

print("Vetor rotacionado: ",p_rot)

Vetor não rotacionado:  [5 7 8]
Vetor rotacionado:  [8.792 7.261 2.825]
