# Trabalho Extra robôtica 

## 1) Importat bibliotecas necessárias 


In [2]:
import numpy as np 

## 2) MTHs do robô Scara 


In [19]:

def MTHS(theta1, theta2, theta3, l1, l2, l0, c):
    theat1_rad = np.radians(theta1)
    theat2_rad = np.radians(theta2)
    theat3_rad = np.radians(theta3)
    T01 = np.matrix([[np.cos(theat1_rad), -np.sin(theat1_rad), 0, l1*np.cos(theat1_rad)], 
                    [np.sin(theat1_rad), np.cos(theat1_rad), 0, l1*np.sin(theat1_rad)],
                    [0, 0, 1, 0], 
                    [0, 0, 0, 1]])
    T12 = np.matrix([[np.cos(theat2_rad), np.sin(theat2_rad), 0, l2*np.cos(theat2_rad)], 
                    [np.sin(theat2_rad), -np.cos(theat1_rad), 0, l2*np.sin(theat2_rad)],
                    [0, 0, -1, 0], 
                    [0, 0, 0, 1]])
    T23 = np.matrix([[1, 0, 0, 0], 
                    [0, -1, 0, 0],
                    [0, 0, -1, c], 
                    [0, 0, 0, 1]])
    T34 = np.matrix([[np.cos(theat3_rad), -np.sin(theat3_rad), 0, 0], 
                    [np.sin(theat3_rad), np.cos(theat3_rad), 0, 0],
                    [0, 0, 1, l0], 
                    [0, 0, 0, 1]])

    T04 = np.matmul(np.matmul(np.matmul(T01, T12), T23), T34);

    print(T04)

MTHS(40, 20, 10, 250, 230, 100, 10)

[[ 3.61402561e-01 -8.29769466e-01  0.00000000e+00  3.06511111e+02]
 [ 9.16593554e-01  2.11018828e-01  0.00000000e+00  3.59882745e+02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  9.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## 3) Cinemática inversa em relação ao punho

![Robô Scara](./ScaraDH.jpg)

In [23]:
def cinematInversa(x, y, l1 = 250, l2 = 230):
    cos_theata2 = np.divide(np.power(x, 2) + np.power(y, 2) - np.power(l1, 2) - np.power(l2, 2), 2*l1*l2)
    theta2_rad = np.arctan2(np.sqrt(1 - np.power(cos_theata2, 2)), cos_theata2)
    theta1_rad = np.arctan2(y, x) - np.arctan2(l2*np.sin(theta2_rad), l1 + l2*np.cos(theta2_rad))


    print("Angulo da junta 1: ", np.rad2deg(theta1_rad))
    print("Angulo da junta 2: ", np.rad2deg(theta2_rad))

cinematInversa(200, 400)

Angulo da junta 1:  43.04772552109242
Angulo da junta 2:  42.63764729078552


## 4) Definir valores dos parâmetros de DH 


thetai | di  | ai | alphai |  
------ | --- | ---| --- |
theta1 | 0  | 250 | 0 |
theta2 | 0  | 230 | 180 |
0      | C | 0   | 180 |
theta3 | 100| 0   | 0 |


## 5) Cinemática inversa de uma trajetoria circular 

In [22]:
x = float(input("Entre com a posição do em punho em x: "))
y = float(input("Entre com a posição do em punho em y: "))

cinematInversa(x, y)

Angulo da junta 1:  43.04772552109242
Angulo da junta 2:  42.63764729078552
